services:
    app:
        build: .
        container_name: ${CONTAINER_NAME}
        restart: unless-stopped
        expose:
            - ${APP_PORT}:80
        env_file:
            - .env
        networks:
          - default
          - proxy
networks:
  proxy:
    external: true
